name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          distribution: 'temurim'
          java-version: '11'
      - name: Build project
        run: mvn clean install -DskipTests


